module.exports = {
    'The Abarat': {},
    'Abeir-Toril': {},
    'All-World': {},
    'Arda': {},
    'Atlantis': {},
    'Avalon': {},
    'Azeroth': {},
    'Broken Empire': {},
    'Camelot': {},
    'Dreamlands': {},
    'Ember': {},
    'Eternia': {},
    'Everworld': {},
    'The Four Lands': {},
    'Hyrule': {},
    'Inkworld': {},
    'The Multiverse': {},
    'Narnia': {},
    'Neverland': {},
    'Oz': {},
    'Oompa - Loompa Land': {},
    'Panem': {},
    'The Shadow Isles': {},
    'Tyria': {},
    'Westeros': {},
    'Xanadu': {},
    'The Nether Ocean': {},
    'The Ancestor Plane': {},
    'The Slumbering Realm': {},
    'The Dormant Isle': {}
    'Stunanica': {},
    'Weaqumar': {},
    'Izearyon': {},
    'Classorath': {},
    'Eayusia': {},
    'The Undying Moon': {},
    'The Nebula Dominion': {},
    'The Past Realms': {},
    'The Dual Territories': {},
    'The Harsh Realms': {},
    'The Steam Terrain': {},
    'The Ethereal Sea': {},
    'The Flowing Lake': {},
    'The Whole Forest': {},
    'The Never Yonder': {},
    'The Legend Yonder': {}
    'Eoqonor': {},
    'Ashodore': {},
    'Imonium': {},
    'Eniola': {},
    'Plotodore': {},
    'Eoxeorat': {},
    'Drowavion': {},
    'Vreasonica': {},
    'Eacrilon': {},
    'Iaccarat': {},
    'The Peaceful Yonder': {},
    'The Broken Sanctum': {},
    'The Bone Domain': {},
    'The Immortal Plane': {},
    'The Obsidian Earth': {}
}